// Generated by CoffeeScript 1.6.3
(function() {
  cryptical.controller('ButtonsCtrl', [
    '$scope', 'crossword', function($scope, crossword) {
      $scope.crossword = crossword;
      $scope.load = function(url) {
        return $http.get(url).success(function(data, status, headers, config) {
          console.log('got json:', data, typeof data);
          return $scope.crossword = new Crossword(data);
        }).error(function(data, status, headers, config) {
          return console.error(status, data);
        });
      };
      $scope.save = function() {
        console.log('sending the following:', crossword.serialise());
        return $http.post('/game/save').success(function(data) {
          return console.log('got response:', data, typeof data);
        }).error(function(data, status, headers, config) {
          return console.error(status, data);
        });
      };
      $scope.load_local = function() {
        var data;
        data = localStorage['crossword'];
        console.log('attempting to parse JSON...');
        data = JSON.parse(localStorage['crossword']);
        return console.log(data);
      };
      return $scope.save_local = function() {
        var data;
        data = crossword.serialise();
        console.log('saving this locally:', data);
        return localStorage['crossword'] = data;
      };
    }
  ]);

}).call(this);
